@localhost = http://localhost:3320

Get {{localhost}}/tasks

###
Get {{localhost}}/tasks/2

###
GET {{localhost}}/tasks/count

###
POST {{localhost}}/tasks HTTP/1.1
Content-Type: application/json

{
    "title":"ki tarea",
    "description":"ceradfg descrip"
}

###
Delete {{localhost}}/tasks/9

###
PUT {{localhost}}/tasks/9 HTTP/1.1
Content-Type: application/json

{
    "title":"updated title",
    "description":"udated 2dfg descrip"
}

###
Get {{localhost}}/blogs

###
Get {{localhost}}/blogs/5

###
POST {{localhost}}/blogs HTTP/1.1
Content-Type: application/json

{
    "title":"Ejemplo blog",
    "body":"lorem gfdj dfgkdf",
    "author":"chanchis"
}

###
Delete {{localhost}}/blogs/2